### ISSUE TITLE
训练异常

### ISSUE THREAD

**Issue by lx86110** [wwxu21/CUT#4]
训练经过第一个样本后就会卡住
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
{'loss': 0.6894, 'learning_rate': 4.000000000000001e-06, 'epoch': 0.0}                                                                                                                             
  0%|▏                                                                                                                                                          | 1/1151 [00:04<1:29:15,  4.66s/it]/usr/local/lib/python3.8/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[E ProcessGroupNCCL.cpp:828] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=37, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1802339 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:828] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=37, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1802220 milliseconds before timing out.
ai-node-i-ycwg2tzshsqc6il45qda:22094:23204 [4] NCCL INFO [Service thread] Connection closed by localRank 4
[E ProcessGroupNCCL.cpp:828] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=37, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1802760 milliseconds before timing out.
ai-node-i-ycwg2tzshsqc6il45qda:22092:23106 [0] NCCL INFO comm 0x3a2abaa0 rank 2 nranks 8 cudaDev 2 busId 69000 - Abort COMPLETE
ai-node-i-ycwg2tzshsqc6il45qda:22094:23109 [0] NCCL INFO comm 0xbd14350 rank 4 nranks 8 cudaDev 4 busId b3000 - Abort COMPLETE
[E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'

Traceback (most recent call last):
  File "finetune_unlikelihood.py", line 558, in <module>
    fire.Fire(train)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "finetune_unlikelihood.py", line 547, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1553, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 1835, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/trainer.py", line 2690, in training_step
    self.accelerator.backward(loss)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 1985, in backward
    loss.backward(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: NCCL communicator was aborted on rank 7.  Original reason for failure was: [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=36, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1803931 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:828] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=37, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1804929 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:828] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=37, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1804265 milliseconds before timing out.
ai-node-i-ycwg2tzshsqc6il45qda:22096:23124 [0] NCCL INFO comm 0x50f0b560 rank 6 nranks 8 cudaDev 6 busId d5000 - Abort COMPLETE

**Comment by lx86110** [comment]
单机8卡，配置和仓库代码一致

**Comment by wwxu21** [comment]
这看起来是NCCL在多GPU通信上出了问题。很大概率是cuda的问题（我实验使用的的cuda环境是cu117），请问你在使用该cuda跑其他多卡任务能进行么？

**Comment by lx86110** [comment]
其他多卡都是正常的，很奇怪
